version: '3.8'

networks:
  app_log:
    driver: bridge

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - app_log 


  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./logs/combined.log:/logs/combined.log
      - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    ports:
      - 9080:9080 
    depends_on:
      - loki
    networks:
      - app_log 


  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - app_log 

